Fixed problem when there's ".header on" option set in ~/.sqlite
(merged)

svn path=/trunk/koffice/; revision=611230

diff --git a/kexi/tools/add_column/ksqlite_add_column b/kexi/tools/add_column/ksqlite_add_column
--- a/kexi/tools/add_column/ksqlite_add_column
+++ b/kexi/tools/add_column/ksqlite_add_column
@@ -50,6 +50,8 @@ if [ $# -lt 4 ] ; then
 	exit 0
 fi
 
+ksqlite="ksqlite -noheader"
+
 database_name=$1
 table_name=$2
 new_column_name=$3
@@ -76,26 +78,25 @@ esac
 
 temp_db=`mktemp "$database_name"XXXXXXXX`
 cp $database_name $temp_db || exit_with_error
-echo "DROP TABLE '$table_name';" | ksqlite "$temp_db" || exit_with_error
+echo "DROP TABLE '$table_name';" | $ksqlite "$temp_db" || exit_with_error
 
 # 1. Receate table with a new field appended
-echo ".schema '$table_name';" | ksqlite "$database_name" | grep "^CREATE TABLE $table_name " | \
- sed -e "s/);/, $new_column_name $new_column_type);/g" | ksqlite "$temp_db" || exit_with_error
+echo ".schema '$table_name';" | $ksqlite "$database_name" | grep "^CREATE TABLE $table_name " | \
+ sed -e "s/);/, $new_column_name $new_column_type);/g" | $ksqlite "$temp_db" || exit_with_error
 
 # 2.1. Get table's ID
 table_id=`echo "SELECT o_id FROM kexi__objects WHERE o_type=1 AND o_name='$table_name';" | \
- ksqlite "$temp_db" || exit_with_error`
+ $ksqlite "$temp_db" || exit_with_error`
 
 # 2.2. Get new field's order
-order=`echo "SELECT MAX(f_order)+1 FROM kexi__fields where t_id=$table_id;" | \
- ksqlite "$temp_db" || exit_with_error`
+order=`echo "SELECT MAX(f_order)+1 FROM kexi__fields WHERE t_id=$table_id;" | $ksqlite "$temp_db" || exit_with_error`
 
 # 2.3. Add the new column information to kexi__fields metadata table
-echo "INSERT INTO kexi__fields (t_id, f_type, f_name, f_length, f_precision, f_constraints, f_options, f_default, f_order, f_caption, f_help) VALUES ($table_id, $typenum, '$new_column_name', 0, 0, 0, 0, NULL, $order, '$new_column_caption', NULL);" | ksqlite "$temp_db" || exit_with_error
+echo "INSERT INTO kexi__fields (t_id, f_type, f_name, f_length, f_precision, f_constraints, f_options, f_default, f_order, f_caption, f_help) VALUES ($table_id, $typenum, '$new_column_name', 0, 0, 0, 0, NULL, $order, '$new_column_caption', NULL);" | $ksqlite "$temp_db" || exit_with_error
 
 # 3. Copy the old data
-echo ".dump '$table_name';" | ksqlite "$database_name" | grep -v "^CREATE TABLE " | \
- sed -e "s/\(^INSERT.*\));$/\\1, NULL);/g" | ksqlite "$temp_db" || exit_with_error
+echo ".dump '$table_name';" | $ksqlite "$database_name" | grep -v "^CREATE TABLE " | \
+ sed -e "s/\(^INSERT.*\));$/\\1, NULL);/g" | $ksqlite "$temp_db" || exit_with_error
 
 # 4. Copy the original database file to .old file and replace the original with the new one
 cp "$database_name" "$database_name.old" || exit_with_error
